[package]
name = "elfio-rs"
version = "0.1.0"
authors = ["Serge Lamikhov-Center <to_serge@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
